### ISSUE TITLE
Measure problematic package(s)

### ISSUE THREAD

**Issue by tj** [pwaller/goimports-update-ignore#2] opened 2016-07-18 21:21 UTC
Awesome program, though even after applying this I still have hundreds of thousands of packages haha and it takes about 15s to run goimports. It would be awesome to have some output that lets you know which are wasting time, I could probably remove a lot of them.

**Comment by pwaller** [comment] 2016-07-18 21:32
Not really sure what to suggest or how I can help. I don't have that problem exactly, so it will be difficult for me to reproduce. You can try inspecting the output of `goimports -v <<<$'package main\nvar _ = thisPackageDoesNotExist328955Z828592.X()'`, for example, which might give you a hint.

Do you have lots of go code checked out? What does your directory structure look like? Can you give a hint of the number of files, number of go projects, etc?

What does `goimports-update-ignore` report at the moment?

**Comment by tj** [comment] 2016-07-18 22:05
Would you be interested in a pull-request for `--measure-only` to maybe show some stats at different depths (or something like that)? I did an ignore at a depth of 10 and still get:

```
Ignored 857 directories. goimports considers 169092 directories in 24887ms (cpu=19776ms).
```

**Comment by pwaller** [comment] 2016-07-18 22:06
Very much so :)

**Comment by pwaller** [comment] 2017-02-15 20:29
Hi @tj. I presume you found a decent alternative workaround, so I'm going to close this for now since there is nothing immediately actionable here. Pull requests are welcome though! :)

**Closed as completed by pwaller** 2017-02-15 20:29 UTC
